### ISSUE TITLE
Build error: ./include/linux/alloc_tag.h:140:1: error: expected identifier before ‘(’ token

### ISSUE THREAD

**Issue by Valmar33** [koverstreet/bcachefs#562]
First bad commit is https://github.com/koverstreet/bcachefs/commit/7b99d9ffd90a6b4a8a1dab47092a061f6ce12250 : `7b99d9ffd90a6b4a8a1dab47092a061f6ce12250` `mm: enable page allocation tagging` 

```
In file included from ./include/linux/percpu.h:5,
                 from ./include/linux/percpu_counter.h:14,
                 from ./include/linux/mm_types.h:21,
                 from ./include/linux/mmzone.h:22,
                 from ./include/linux/gfp.h:7,
                 from ./include/linux/mm.h:7,
                 from ./include/linux/scatterlist.h:8,
                 from ./include/linux/dma-buf.h:19,
                 from drivers/accel/ivpu/ivpu_gem.c:6:
drivers/accel/ivpu/ivpu_gem.c: In function ‘ivpu_bo_alloc_and_map_pages_locked’:
./include/linux/alloc_tag.h:140:1: error: expected identifier before ‘(’ token
  140 | ({                                                                      \
      | ^
./include/linux/gfp.h:288:49: note: in expansion of macro ‘alloc_hooks’
  288 | #define alloc_pages(...)                        alloc_hooks(alloc_pages_noprof(__VA_ARGS__))
      |                                                 ^~~~~~~~~~~
drivers/accel/ivpu/ivpu_gem.c:200:24: note: in expansion of macro ‘alloc_pages’
  200 |         ret = bo->ops->alloc_pages(bo);
      |                        ^~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:252: drivers/accel/ivpu/ivpu_gem.o] Error 1
make[4]: *** Waiting for unfinished jobs....
```

**Comment by hardfalcon** [comment]
This issue was fixed by commit 04f2d2ae5bd69eecd0b4bb700efdc665b09745a1.

However, in the meantime, some other bcachefs commit, most likely the new commit 400b3ab05c646cc14a8953f72c7ae2218d92da87, breaks compiling for me in several other places.

I'll open a separate issue for that.

**Comment by Valmar33** [comment]
Will test :)

**Comment by Valmar33** [comment]
@hardfalcon This is still an issue. That commit doesn't seem to fix it for me. :/

**Comment by Valmar33** [comment]
@hardfalcon

> This issue was fixed by commit https://github.com/koverstreet/bcachefs/commit/04f2d2ae5bd69eecd0b4bb700efdc665b09745a1.

Looking at this commit further, it cannot fix my issue, because this commit was introduced before the commit that causes my build failure.

**Comment by Valmar33** [comment]
Re-opened so that YellowOnion is assigned as bug wrangler.

**Comment by marcin-github** [comment]
There is no commit 7b99d9ffd90a6 , did you updated sources to the latest master? Which commit is newest for you?

**Comment by Valmar33** [comment]
@marcin-github 

I'll check... there's been enough rebases lately that keeping up with it is tricky.
